### ISSUE TITLE
Windows 8 Support?

### ISSUE THREAD

**Issue by juristr** [lepht/licecap#7]
Hi,

will there be support for Windows 8?? I use it on OSX and Win7, and just tried it on my new win8.1 surface and had a strange behavior. While the recording worked, it seems to not record the right area under the Licecap window, but instead an area further above the desired recording area.

Any idea on how to fix this?

**Comment by smeijer** [comment]
Happens to me also. Too bad, because it makes the tool kind of useless.

recording area
![recording area](http://i.imgur.com/l00gzNR.png)

recording result
![recording result](http://i.imgur.com/wopFSXe.gif)

**Comment by juristr** [comment]
would be really awesome if this gets fixed

**Comment by smeijer** [comment]
Disabling dpi scaling in the .exe's compatibility properties, fixes the problem. So there is a work around.

**Comment by juristr** [comment]
@smeijer Awesome!! :clap:  Thx a lot!!
